project:
  type: website

website:
  site-url: https://stat243.berkeley.edu/fall-2024
  sidebar:
    style: docked
    title: "Stat 243"
    logo: assets/stat_bear.png
    logo-alt: "UC Berkeley Statistics logo"
    tools:
      - icon: github
        href: https://github.com/berkeley-stat243/fall-2024
        aria-label: GitHub
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: office_hours.qmd
        text: Office Hours
      - section: "Units"
        contents:
          - href: units/unit1-intro.qmd
            text: "Unit 1 (UNIX intro)"
          - href: units/unit2-dataTech.qmd
            text: "Unit 2 (Data technologies)"
          - href: units/unit3-bash.qmd
            text: "Unit 3 (Bash shell)"
          - href: units/unit4-goodPractices.qmd
            text: "Unit 4 (Good practices)"
          - href: units/unit5-programming.qmd
            text: "Unit 5 (Programming)"
          - href: units/unit6-parallel.qmd
            text: "Unit 6 (Parallelization)"
          - href: units/unit7-bigData.qmd
            text: "Unit 7 (Databases)"
          - href: units/unit8-numbers.qmd
            text: "Unit 8 (Precision)"
          - href: units/unit9-sim.qmd
            text: "Unit 9 (Simulation)"
          - href: units/unit10-linalg.qmd
            text: "Unit 10 (Linear Algebra)"
      - section: "Labs"
        contents:
          - href: labs/lab0-setup.html
            text: "Lab 0 (Optional setup)"
          - href: labs/lab1-submission.html
            text: "Lab 1 (Quarto/Git/Submission)"
          - href: labs/lab2-testing.html
            text: "Lab 2 (Exceptions/Testing)"
          - href: labs/lab3-debugging.html
            text: "Lab 3 (Debugging)"
          - href: labs/lab4-reproducibility.html
            text: "Lab 4 (Reproducibility)"
          - href: labs/lab5-codereview.html
            text: "Lab 5 (Code review)"
          - href: labs/lab6-scfparallel.html
            text: "Lab 6 (SCF and parallelization)"
          - href: labs/lab7-pythonvsr.html
            text: "Lab 7 (Python vs. R)"
          - href: labs/lab8-simulation.html
            text: "Lab 8 (Simulation)"
      - section: "Problem Sets"
        contents:
          - href: ps/ps1.qmd
          - href: ps/ps2.qmd
          - href: ps/ps3.qmd
          - href: ps/ps4.qmd
          - href: ps/ps5.qmd
          - href: ps/ps6.qmd
          - href: ps/ps7.qmd
      - section: "How tos"
        contents:
          - howtos/accessPython.md
          - howtos/accessUnixCommandLine.md
          - howtos/installGit.md
          - howtos/installQuarto.md
          - howtos/submitPS.md
          - howtos/windowsAndLinux.md
      - href: license.qmd
        text: License
          
format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true

execute:
  freeze: auto

